import { createTool } from '@mastra/core/tools';
import { z } from 'zod';
import axios from 'axios';
import crypto from 'crypto';
import { env } from '../../config/env.js';
import { logger } from '../../config/logger.js';

export const sendSlackMessageTool = createTool({
  id: 'sendSlackMessage',
  description: 'Posts a structured Slack message about a validated action item',
  inputSchema: z.object({
    channel: z.string().optional(),
    meetingTitle: z.string(),
    actionItemDescription: z.string(),
    assignee: z.string(),
    deadline: z.string().nullable(),
    priority: z.enum(['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']),
    jiraUrl: z.string().optional(),
    meetingId: z.string(),
  }),
  outputSchema: z.object({
    messageId: z.string(),
    success: z.boolean(),
    error: z.string().optional(),
  }),
  execute: async ({ context }) => {
    const { channel, meetingTitle, actionItemDescription, assignee, deadline, priority, jiraUrl, meetingId } = context;

    if (!env.SLACK_BOT_TOKEN) {
      logger.warn('Slack not configured', { meetingId });
      return { messageId: '', success: false, error: 'Slack not configured' };
    }

    const PRIORITY_EMOJI: Record<string, string> = {
      CRITICAL: '🔴',
      HIGH: '🟠',
      MEDIUM: '🟡',
      LOW: '🟢',
    };

    const blocks = [
      {
        type: 'header',
        text: { type: 'plain_text', text: `${PRIORITY_EMOJI[priority]} Synapse Action Item — ${meetingTitle}` },
      },
      {
        type: 'section',
        fields: [
          { type: 'mrkdwn', text: `*Task:*\n${actionItemDescription}` },
          { type: 'mrkdwn', text: `*Assignee:*\n${assignee}` },
          { type: 'mrkdwn', text: `*Deadline:*\n${deadline ?? 'Not specified'}` },
          { type: 'mrkdwn', text: `*Priority:*\n${priority}` },
        ],
      },
      ...(jiraUrl ? [{
        type: 'actions',
        elements: [{
          type: 'button',
          text: { type: 'plain_text', text: '📋 View Jira Ticket' },
          url: jiraUrl,
        }],
      }] : []),
      {
        type: 'context',
        elements: [{ type: 'mrkdwn', text: `🤖 Generated by Synapse AI • Meeting ID: ${meetingId}` }],
      },
    ];

    try {
      const response = await axios.post(
        'https://slack.com/api/chat.postMessage',
        {
          channel: channel ?? env.SLACK_DEFAULT_CHANNEL,
          blocks,
          text: `Action item for ${assignee}: ${actionItemDescription}`, // Fallback
        },
        {
          headers: {
            Authorization: `Bearer ${env.SLACK_BOT_TOKEN}`,
            'Content-Type': 'application/json',
          },
          timeout: 10000,
        }
      );

      if (!response.data.ok) {
        throw new Error(response.data.error ?? 'Slack API error');
      }

      const messageId = response.data.ts as string;
      logger.info('Slack message sent', { messageId, channel });
      return { messageId, success: true };
    } catch (error) {
      const msg = (error as Error).message;
      logger.error('Slack message failed', { error: msg });
      return { messageId: '', success: false, error: msg };
    }
  },
});
